### PR TITLE
Tweak the design

### PR DESCRIPTION
**Pull request by thorsteinsson**
tweaks

### CODE REVIEW

**Comment by thorsteinsson** [comment]
I changed `Studio feed` title to `What's happening`

**Comment by davidblurton** [comment]
This is looking nice! Definitely an improvement.

**Comment by eirikurn** [comment]
lgtm. Tagline might pop out a bit more, not sure how but looked better before (i think)

**Comment by thorsteinsson** [comment]
I got rid of the yellow footer.
more-tweaks

**Pull request merged**
