### PR TITLE
Feed improvement

### PR DESCRIPTION
**Pull request by thorsteinsson**
A better image for the jsis event and remove the text “Facebook” from items.

image

### CODE REVIEW

**Comment by rthor** [comment]
Why is the date green?

**Comment by thorsteinsson** [comment]
It wasn't supposed to be green, feel free to suggest a better color. The current one is too dark.

**Comment by thorsteinsson** [comment]
Fixed, @rthor PTAL

**Comment by rthor** [comment]
LGTM!

**Pull request merged**
